global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx_exporter'
    static_configs:
      - targets:
          - nginx_exporter:9113

  - job_name: 'web_servers'
    static_configs:
      - targets:
          - web1_exporter:9100
          - web2_exporter:9100
